[package]
name = "bookshelf-api"
version = "1.0.0"
edition = "2021"
authors = ["Aksiome"]
description = "REST API for the Bookshelf project"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.93"
axum = "0.7.7"
cached = { version = "0.54.0", features = ["async"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
zip = "2.2.0"

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1
