name: 🔨 Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add x86_64-unknown-linux-musl
      - run: curl -O https://musl.openssl.org/openssl-musl.tar.gz
      - run: tar xvf openssl-musl.tar.gz
      - run: export OPENSSL_DIR=$(pwd)/openssl-musl
      - run: cargo build --target x86_64-unknown-linux-musl --verbose --release
      - uses: actions/upload-artifact@v4
        with:
          name: bookshelf-api
          path: target/x86_64-unknown-linux-musl/release/bookshelf-api
