name: 🔨 Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose --release
      - uses: actions/upload-artifact@v4
        with:
          name: bookshelf-api
          path: target/release/bookshelf-api
