name: 🔨 Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: 
      - "master"
    tags:
      - "v*"
  schedule:
    - cron: "54 3 * * *"
jobs:
  build:
    name: Build and Publish Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set_tag
        run: |
          # Définir le tag selon le contexte
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Si c'est un tag Git, on utilise le tag comme version
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
          else
            # Sinon, on utilise "latest" pour les commits sur master
            IMAGE_TAG="latest"
          fi

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:bookshelf-api-${{ env.IMAGE_TAG }}
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          # Build the image
          docker build -t $IMAGE_NAME_LOWER .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: |
          # Push the image to GitHub Packages with the appropriate tag
          docker push $IMAGE_NAME_LOWER
